# Generated by Django 5.0.7 on 2024-07-30 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShitrPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=30)),
                ('rating', models.FloatField()),
            ],
        ),
    ]
