# Generated by Django 5.0.7 on 2024-08-01 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shitr_posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shitrpost',
            name='rating',
        ),
        migrations.AddField(
            model_name='shitrpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='1970-01-01 00:00:00+00:00'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ShitrReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comfort', models.FloatField()),
                ('smell', models.FloatField()),
                ('aesthetic', models.FloatField()),
                ('toilet_paper', models.FloatField()),
                ('overal_experience', models.FloatField()),
                ('description', models.TextField(max_length=280)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='shitr_posts.shitrpost')),
            ],
        ),
    ]
