# Generated by Django 5.0.7 on 2024-08-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shitr_posts', '0002_remove_shitrpost_rating_shitrpost_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shitrpost',
            name='aesthetic',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shitrpost',
            name='comfort',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shitrpost',
            name='description',
            field=models.TextField(default='None', max_length=280),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shitrpost',
            name='overal_experience',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shitrpost',
            name='post_name',
            field=models.CharField(default='None', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shitrpost',
            name='smell',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shitrpost',
            name='toilet_paper',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ShitrReview',
        ),
    ]
