# Generated by Django 5.0.7 on 2024-08-01 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shitr_posts', '0003_shitrpost_aesthetic_shitrpost_comfort_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shitrpost',
            name='description',
            field=models.TextField(blank=True, max_length=280),
        ),
    ]
