# Generated by Django 5.0.7 on 2024-08-01 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shitr_posts', '0004_alter_shitrpost_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shitrpost',
            old_name='overal_experience',
            new_name='overall_experience',
        ),
    ]
