FROM python 

# Create the django directory
RUN mkdir /opt/django

WORKDIR /opt/django
COPY . /opt/django

# Install the packages
RUN pip install -r /opt/django/requirements.txt

EXPOSE 8081

# Run the django server
CMD ["python3", "manage.py", "runserver", "0.0.0.0:8001"]