# Generated by Django 5.0.7 on 2024-07-29 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shitr_users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='customuser',
            name='password',
            field=models.CharField(default='test', max_length=30),
        ),
    ]
