version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: shitr
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/opt/django/
    ports:
      - "8081:8000"
    depends_on:
      - db

volumes:
  postgres_data:

